fail_fast: false
default_language_version:
    python: python3
default_stages:
-   commit
-   push
minimum_pre_commit_version: 2.9.3
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        additional_dependencies: [numpy==1.20.0, scipy, pandas, types-requests]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        additional_dependencies: [toml]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        additional_dependencies: [toml]
        args: [--order-by-type]
# temporarily disable yesqa, because of: ValueError: not enough values to unpack (expected 2, got 1).
# Possibly related to https://github.com/asottile/yesqa/issues/132
#-   repo: https://github.com/asottile/yesqa
#    rev: v1.4.0
#    hooks:
#    -   id: yesqa
#        additional_dependencies: [flake8-tidy-imports, flake8-docstrings, flake8-rst-docstrings, flake8-comprehensions, flake8-bugbear, flake8-logging-format, flake8-blind-except, flake8-builtins, flake8-pytest-style, flake8-mock, flake8-string-format]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-symlinks
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace
        exclude: ^.bumpversion.cfg$
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: check-toml
    -   id: requirements-txt-fixer
-   repo: https://github.com/myint/autoflake
    rev: v1.7.7
    hooks:
    -   id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variable, --ignore-init-module-imports]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-tidy-imports, flake8-docstrings, flake8-rst-docstrings, flake8-comprehensions, flake8-bugbear, flake8-logging-format, flake8-blind-except, flake8-builtins, flake8-pytest-style, flake8-mock, flake8-string-format]
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
    -   id: script-must-have-extension
        name: Check executable files use .sh extension
        types: [shell, executable]
# YAML files
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: pretty-format-yaml
        args: [--autofix, --indent, '4']
# docs (md/rst files)
#-   repo: https://github.com/myint/rstcheck
#    rev: v6.1.0
#    hooks:
#    -   id: rstcheck
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.10.0]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus, --py37-plus]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-no-eval
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
-   repo: https://github.com/PyCQA/doc8
    rev: v1.0.0
    hooks:
    -   id: doc8
# jupyter notebooks
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.3
    hooks:
    -   id: nbqa-black
        additional_dependencies: [black==22.10.0]
    -   id: nbqa-isort
        additional_dependencies: [isort==5.9.1]
        args: [--order-by-type]
    -   id: nbqa
        entry: nbqa autoflake
        name: nbqa-autoflake
        alias: nbqa-autoflake
        additional_dependencies: [autoflake==v1.7.7]
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variable, --ignore-init-module-imports]
    -   id: nbqa-flake8
        additional_dependencies: [flake8==3.9.2, flake8-tidy-imports, flake8-docstrings, flake8-rst-docstrings, flake8-comprehensions, flake8-bugbear, flake8-logging-format, flake8-blind-except, flake8-builtins, flake8-pytest-style, flake8-mock, flake8-string-format]
    -   id: nbqa-pyupgrade
        args: [--py3-plus, --py37-plus]
        additional_dependencies: [pyupgrade==v3.1.0]
